// <auto-generated />
using System;
using Gp.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gp.Infra.Migrations
{
    [DbContext(typeof(GpContext))]
    [Migration("20240503032018_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDespesa")
                        .HasColumnType("int");

                    b.Property<float>("ValorPrevisto")
                        .HasColumnType("real");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("Despesa");
                });

            modelBuilder.Entity("Gp.Domain.Models.DespesaLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DespesaId")
                        .HasColumnType("int");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DespesaId");

                    b.ToTable("DespesaLancamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MesDoAno")
                        .HasColumnType("int");

                    b.Property<float>("ValorTotalDespesas")
                        .HasColumnType("real");

                    b.Property<float>("ValorTotalReceitas")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Orcamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2024,
                            DataCriacao = new DateTime(2024, 5, 3, 0, 20, 17, 922, DateTimeKind.Local).AddTicks(8594),
                            Descricao = "Viagem Cuiabá Férias",
                            MesDoAno = 7,
                            ValorTotalDespesas = 0f,
                            ValorTotalReceitas = 0f
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2024,
                            DataCriacao = new DateTime(2024, 5, 3, 0, 20, 17, 922, DateTimeKind.Local).AddTicks(8610),
                            Descricao = "Despesa Mensal",
                            MesDoAno = 5,
                            ValorTotalDespesas = 0f,
                            ValorTotalReceitas = 0f
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<int>("TIpoReceita")
                        .HasColumnType("int");

                    b.Property<float>("ValorPrevisto")
                        .HasColumnType("real");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("Gp.Domain.Models.ReceitaLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitaLancamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.HasOne("Gp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany("Despesas")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.DespesaLancamento", b =>
                {
                    b.HasOne("Gp.Domain.Models.Despesa", "Despesa")
                        .WithMany("DespesaLancamentos")
                        .HasForeignKey("DespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despesa");
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.HasOne("Gp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany("Receitas")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.ReceitaLancamento", b =>
                {
                    b.HasOne("Gp.Domain.Models.Receita", "Receita")
                        .WithMany("ReceitaLancamentos")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.Navigation("DespesaLancamentos");
                });

            modelBuilder.Entity("Gp.Domain.Models.Orcamento", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.Navigation("ReceitaLancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
