// <auto-generated />
using System;
using Gp.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gp.Infra.Migrations
{
    [DbContext(typeof(GpContext))]
    [Migration("20240628125247_testando")]
    partial class testando
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gp.Domain.Auth.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TemporaryPassword")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9552c4b8-e60e-42a6-8f97-96b8f8edd555"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a503903-b30e-4c13-9e8a-2ec6038c475c",
                            Email = "jeancpcorrea@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JEANCPCORREA@GMAIL.COM",
                            NormalizedUserName = "jeancpcorrea@gmail.com",
                            PasswordHash = "@Admin123456",
                            PhoneNumber = "65981324241",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "LDPU32DFTNBNBJ5JQ2R7VXEHNCGE6UER",
                            TemporaryPassword = false,
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDespesa")
                        .HasColumnType("int");

                    b.Property<float>("ValorPrevisto")
                        .HasColumnType("real");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("Despesa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(1690),
                            Descricao = "Gás",
                            OrcamentoId = 2,
                            TipoDespesa = 2,
                            ValorPrevisto = 43.5f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(1712),
                            Descricao = "Aluguel",
                            OrcamentoId = 2,
                            TipoDespesa = 4,
                            ValorPrevisto = 1250f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(1724),
                            Descricao = "Combustivel",
                            OrcamentoId = 2,
                            TipoDespesa = 14,
                            ValorPrevisto = 500f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(1736),
                            Descricao = "Remedios",
                            OrcamentoId = 2,
                            TipoDespesa = 9,
                            ValorPrevisto = 150f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(1744),
                            Descricao = "Luz",
                            OrcamentoId = 2,
                            TipoDespesa = 1,
                            ValorPrevisto = 260f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(1753),
                            Descricao = "CartaoCredito",
                            OrcamentoId = 2,
                            TipoDespesa = 15,
                            ValorPrevisto = 1300f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 7,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(1761),
                            Descricao = "Alimentacao",
                            OrcamentoId = 2,
                            TipoDespesa = 13,
                            ValorPrevisto = 1000f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 8,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(1771),
                            Descricao = "Condominio",
                            OrcamentoId = 2,
                            TipoDespesa = 5,
                            ValorPrevisto = 450f,
                            ValorTotal = 0f
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.DespesaLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DespesaId")
                        .HasColumnType("int");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DespesaId");

                    b.ToTable("DespesaLancamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("Livro", (string)null);
                });

            modelBuilder.Entity("Gp.Domain.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MesDoAno")
                        .HasColumnType("int");

                    b.Property<float>("ValorTotalDespesas")
                        .HasColumnType("real");

                    b.Property<float>("ValorTotalReceitas")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Orcamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2024,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(5389),
                            Descricao = "Viagem Cuiabá Férias",
                            MesDoAno = 7,
                            ValorTotalDespesas = 0f,
                            ValorTotalReceitas = 0f
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2024,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(5394),
                            Descricao = "Despesa Mensal",
                            MesDoAno = 5,
                            ValorTotalDespesas = 0f,
                            ValorTotalReceitas = 0f
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<int>("TIpoReceita")
                        .HasColumnType("int");

                    b.Property<float>("ValorPrevisto")
                        .HasColumnType("real");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("Receita");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(3828),
                            Descricao = "SalarioJean",
                            OrcamentoId = 2,
                            TIpoReceita = 1,
                            ValorPrevisto = 3240f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(3840),
                            Descricao = "FlexBenner",
                            OrcamentoId = 2,
                            TIpoReceita = 6,
                            ValorPrevisto = 1250f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2024, 6, 28, 9, 52, 46, 889, DateTimeKind.Local).AddTicks(3848),
                            Descricao = "Bpc",
                            OrcamentoId = 2,
                            TIpoReceita = 2,
                            ValorPrevisto = 1450f,
                            ValorTotal = 0f
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.ReceitaLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitaLancamento");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("078a8c6e-a76d-46e8-ba75-3e9476c0a35c"),
                            UserId = new Guid("9552c4b8-e60e-42a6-8f97-96b8f8edd555")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.HasOne("Gp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany("Despesas")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.DespesaLancamento", b =>
                {
                    b.HasOne("Gp.Domain.Models.Despesa", "Despesa")
                        .WithMany("DespesaLancamentos")
                        .HasForeignKey("DespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despesa");
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.HasOne("Gp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany("Receitas")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.ReceitaLancamento", b =>
                {
                    b.HasOne("Gp.Domain.Models.Receita", "Receita")
                        .WithMany("ReceitaLancamentos")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.Navigation("DespesaLancamentos");
                });

            modelBuilder.Entity("Gp.Domain.Models.Orcamento", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.Navigation("ReceitaLancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
