// <auto-generated />
using System;
using Gp.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gp.Infra.Migrations
{
    [DbContext(typeof(GpContext))]
    [Migration("20240503155158_seed-receita-despesa")]
    partial class seedreceitadespesa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDespesa")
                        .HasColumnType("int");

                    b.Property<float>("ValorPrevisto")
                        .HasColumnType("real");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("Despesa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(1162),
                            Descricao = "Gás",
                            OrcamentoId = 2,
                            TipoDespesa = 2,
                            ValorPrevisto = 43.5f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(1223),
                            Descricao = "Aluguel",
                            OrcamentoId = 2,
                            TipoDespesa = 4,
                            ValorPrevisto = 1250f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(1247),
                            Descricao = "Combustivel",
                            OrcamentoId = 2,
                            TipoDespesa = 14,
                            ValorPrevisto = 500f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(1264),
                            Descricao = "Remedios",
                            OrcamentoId = 2,
                            TipoDespesa = 9,
                            ValorPrevisto = 150f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(1287),
                            Descricao = "Luz",
                            OrcamentoId = 2,
                            TipoDespesa = 1,
                            ValorPrevisto = 260f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(1301),
                            Descricao = "CartaoCredito",
                            OrcamentoId = 2,
                            TipoDespesa = 15,
                            ValorPrevisto = 1300f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 7,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(1323),
                            Descricao = "Alimentacao",
                            OrcamentoId = 2,
                            TipoDespesa = 13,
                            ValorPrevisto = 1000f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 8,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(1339),
                            Descricao = "Condominio",
                            OrcamentoId = 2,
                            TipoDespesa = 5,
                            ValorPrevisto = 450f,
                            ValorTotal = 0f
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.DespesaLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DespesaId")
                        .HasColumnType("int");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DespesaId");

                    b.ToTable("DespesaLancamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MesDoAno")
                        .HasColumnType("int");

                    b.Property<float>("ValorTotalDespesas")
                        .HasColumnType("real");

                    b.Property<float>("ValorTotalReceitas")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Orcamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2024,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(8177),
                            Descricao = "Viagem Cuiabá Férias",
                            MesDoAno = 7,
                            ValorTotalDespesas = 0f,
                            ValorTotalReceitas = 0f
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2024,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(8193),
                            Descricao = "Despesa Mensal",
                            MesDoAno = 5,
                            ValorTotalDespesas = 0f,
                            ValorTotalReceitas = 0f
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<int>("TIpoReceita")
                        .HasColumnType("int");

                    b.Property<float>("ValorPrevisto")
                        .HasColumnType("real");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("Receita");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(5602),
                            Descricao = "SalarioJean",
                            OrcamentoId = 2,
                            TIpoReceita = 1,
                            ValorPrevisto = 3240f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(5641),
                            Descricao = "FlexBenner",
                            OrcamentoId = 2,
                            TIpoReceita = 6,
                            ValorPrevisto = 1250f,
                            ValorTotal = 0f
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2024, 5, 3, 12, 51, 58, 299, DateTimeKind.Local).AddTicks(5657),
                            Descricao = "Bpc",
                            OrcamentoId = 2,
                            TIpoReceita = 2,
                            ValorPrevisto = 1450f,
                            ValorTotal = 0f
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.ReceitaLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitaLancamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.HasOne("Gp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany("Despesas")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.DespesaLancamento", b =>
                {
                    b.HasOne("Gp.Domain.Models.Despesa", "Despesa")
                        .WithMany("DespesaLancamentos")
                        .HasForeignKey("DespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despesa");
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.HasOne("Gp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany("Receitas")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.ReceitaLancamento", b =>
                {
                    b.HasOne("Gp.Domain.Models.Receita", "Receita")
                        .WithMany("ReceitaLancamentos")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.Navigation("DespesaLancamentos");
                });

            modelBuilder.Entity("Gp.Domain.Models.Orcamento", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.Navigation("ReceitaLancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
