// <auto-generated />
using System;
using Gp.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gp.Infra.Migrations
{
    [DbContext(typeof(GpContext))]
    [Migration("20250428112409_receita")]
    partial class receita
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gp.Domain.Auth.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TemporaryPassword")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9552c4b8-e60e-42a6-8f97-96b8f8edd555"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a503903-b30e-4c13-9e8a-2ec6038c475c",
                            Email = "jeancpcorrea@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JEANCPCORREA@GMAIL.COM",
                            NormalizedUserName = "jeancpcorrea@gmail.com",
                            PasswordHash = "@Admin123456",
                            PhoneNumber = "65981324241",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "LDPU32DFTNBNBJ5JQ2R7VXEHNCGE6UER",
                            TemporaryPassword = false,
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MesReferente")
                        .HasColumnType("int");

                    b.Property<long>("OrcamentoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PorcentagemPaga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoRestante")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoDespesa")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("Despesa");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(5332),
                            Descricao = "Parto do Bebê",
                            MesReferente = 0,
                            OrcamentoId = 4L,
                            PorcentagemPaga = 0m,
                            SaldoRestante = 0m,
                            TipoDespesa = 2,
                            ValorPrevisto = 5000.00m,
                            ValorTotal = 0m
                        },
                        new
                        {
                            Id = 2L,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(5365),
                            Descricao = "Aluguel",
                            MesReferente = 5,
                            OrcamentoId = 2L,
                            PorcentagemPaga = 0m,
                            SaldoRestante = 0m,
                            TipoDespesa = 4,
                            ValorPrevisto = 1050.00m,
                            ValorTotal = 0m
                        },
                        new
                        {
                            Id = 3L,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(5385),
                            Descricao = "Combustível",
                            MesReferente = 5,
                            OrcamentoId = 2L,
                            PorcentagemPaga = 0m,
                            SaldoRestante = 0m,
                            TipoDespesa = 14,
                            ValorPrevisto = 240.00m,
                            ValorTotal = 0m
                        },
                        new
                        {
                            Id = 4L,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(5400),
                            Descricao = "Remédios",
                            MesReferente = 5,
                            OrcamentoId = 2L,
                            PorcentagemPaga = 0m,
                            SaldoRestante = 0m,
                            TipoDespesa = 9,
                            ValorPrevisto = 250.00m,
                            ValorTotal = 0m
                        },
                        new
                        {
                            Id = 5L,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(5416),
                            Descricao = "Fatura de Luz",
                            MesReferente = 5,
                            OrcamentoId = 2L,
                            PorcentagemPaga = 0m,
                            SaldoRestante = 0m,
                            TipoDespesa = 1,
                            ValorPrevisto = 260.00m,
                            ValorTotal = 0m
                        },
                        new
                        {
                            Id = 6L,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(5432),
                            Descricao = "Cartão de Credito",
                            MesReferente = 5,
                            OrcamentoId = 2L,
                            PorcentagemPaga = 0m,
                            SaldoRestante = 0m,
                            TipoDespesa = 15,
                            ValorPrevisto = 4000.00m,
                            ValorTotal = 0m
                        },
                        new
                        {
                            Id = 7L,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(5450),
                            Descricao = "Alimentação",
                            MesReferente = 5,
                            OrcamentoId = 2L,
                            PorcentagemPaga = 0m,
                            SaldoRestante = 0m,
                            TipoDespesa = 13,
                            ValorPrevisto = 1400.00m,
                            ValorTotal = 0m
                        },
                        new
                        {
                            Id = 8L,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(5466),
                            Descricao = "Consorcio",
                            MesReferente = 5,
                            OrcamentoId = 2L,
                            PorcentagemPaga = 0m,
                            SaldoRestante = 0m,
                            TipoDespesa = 5,
                            ValorPrevisto = 480.00m,
                            ValorTotal = 0m
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.DespesaLancamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("DespesaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DespesaId");

                    b.ToTable("DespesaLancamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.Livro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("Livro", (string)null);
                });

            modelBuilder.Entity("Gp.Domain.Models.Orcamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MesDoAno")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotalDespesas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalReceitas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orcamento");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ano = 2026,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(9265),
                            Descricao = "Viagem Cuiabá Férias",
                            MesDoAno = 1,
                            ValorTotalDespesas = 0m,
                            ValorTotalReceitas = 0m
                        },
                        new
                        {
                            Id = 2L,
                            Ano = 2025,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(9273),
                            Descricao = "Despesa Mensal",
                            MesDoAno = 5,
                            ValorTotalDespesas = 0m,
                            ValorTotalReceitas = 0m
                        },
                        new
                        {
                            Id = 3L,
                            Ano = 2025,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(9274),
                            Descricao = "Investimentos",
                            MesDoAno = 0,
                            ValorTotalDespesas = 0m,
                            ValorTotalReceitas = 0m
                        },
                        new
                        {
                            Id = 4L,
                            Ano = 2025,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(9275),
                            Descricao = "Temporário",
                            MesDoAno = 0,
                            ValorTotalDespesas = 0m,
                            ValorTotalReceitas = 0m
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MesReferente")
                        .HasColumnType("int");

                    b.Property<long>("OrcamentoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PorcentagemPaga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoRestante")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TIpoReceita")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("Receita");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(7734),
                            Descricao = "Salário Jean",
                            MesReferente = 0,
                            OrcamentoId = 2L,
                            PorcentagemPaga = 0m,
                            SaldoRestante = 0m,
                            TIpoReceita = 1,
                            ValorPrevisto = 3240.00m,
                            ValorTotal = 0m
                        },
                        new
                        {
                            Id = 2L,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(7765),
                            Descricao = "Flex Benner",
                            MesReferente = 0,
                            OrcamentoId = 2L,
                            PorcentagemPaga = 0m,
                            SaldoRestante = 0m,
                            TIpoReceita = 6,
                            ValorPrevisto = 1250.00m,
                            ValorTotal = 0m
                        },
                        new
                        {
                            Id = 3L,
                            DataCriacao = new DateTime(2025, 4, 28, 8, 24, 7, 390, DateTimeKind.Local).AddTicks(7780),
                            Descricao = "Bpc Lorenzo",
                            MesReferente = 0,
                            OrcamentoId = 2L,
                            PorcentagemPaga = 0m,
                            SaldoRestante = 0m,
                            TIpoReceita = 2,
                            ValorPrevisto = 1450.00m,
                            ValorTotal = 0m
                        });
                });

            modelBuilder.Entity("Gp.Domain.Models.ReceitaLancamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ReceitaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitaLancamento");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("078a8c6e-a76d-46e8-ba75-3e9476c0a35c"),
                            UserId = new Guid("9552c4b8-e60e-42a6-8f97-96b8f8edd555")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.HasOne("Gp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany("Despesas")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.DespesaLancamento", b =>
                {
                    b.HasOne("Gp.Domain.Models.Despesa", "Despesa")
                        .WithMany("DespesaLancamentos")
                        .HasForeignKey("DespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despesa");
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.HasOne("Gp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany("Receitas")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("Gp.Domain.Models.ReceitaLancamento", b =>
                {
                    b.HasOne("Gp.Domain.Models.Receita", "Receita")
                        .WithMany("ReceitaLancamentos")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("Gp.Domain.Models.Despesa", b =>
                {
                    b.Navigation("DespesaLancamentos");
                });

            modelBuilder.Entity("Gp.Domain.Models.Orcamento", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("Gp.Domain.Models.Receita", b =>
                {
                    b.Navigation("ReceitaLancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
