services:
  api:
    image: estacionamento-backend:latest
    container_name: estacionamento-backend-api
    build:
      context: .
      dockerfile: estacionamento-backend.api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PathBase=/estac
      - AutomaticRunDbMigrations=true
      - ConnectionStrings__DefaultConnection=Server=db;Database=gts-desenvolvimento;User=sa;Password=@Admin2134;TrustServerCertificate=True;
      - EstacionamentoWorkers__Enabled=true
      - EstacionamentoWorkers__BaseUrl=http://108.174.145.123:8081
      - EstacionamentoWorkers__TimeoutSeconds=15
    depends_on:
      - db
    networks:
      - estacionamento-backend-network
  db:
    container_name: estacionamento-backend-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=@Admin2134
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - estacionamento-backend-network
networks:
  estacionamento-backend-network:
volumes:
  sql_data:
