<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Estac.Api</RootNamespace>
    <AssemblyName>estacionamento-backend.api</AssemblyName>
	  <Nullable>disable</Nullable>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>dc0caab1-5f77-42b0-9169-12c0c86633ae</UserSecretsId>
	  <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="R\**" />
    <Content Remove="R\**" />
    <EmbeddedResource Remove="R\**" />
    <None Remove="R\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Core" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\estacionamento-backend.crosscutting\estacionamento-backend.crosscutting.csproj" />
    <ProjectReference Include="..\estacionamento-backend.domain\estacionamento-backend.domain.csproj" />
    <ProjectReference Include="..\estacionamento-backend.infra\estacionamento-backend.infra.csproj" />
  </ItemGroup>

</Project>
