<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Estac.Service</RootNamespace>
    <AssemblyName>estacionamento-backend.service</AssemblyName>
	  <Nullable>disable</Nullable>
	  <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.4.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\estacionamento-backend.domain\estacionamento-backend.domain.csproj" />
    <ProjectReference Include="..\estacionamento-backend.infra\estacionamento-backend.infra.csproj" />
  </ItemGroup>

</Project>
