// <auto-generated />
using System;
using Estac.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estac.Infra.Migrations
{
    [DbContext(typeof(GtsContext))]
    [Migration("20260801030709_Utc")]
    partial class Utc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Estac.Domain.Models.ConfiguracaoAgendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ConfiguracaoCobrancaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("DiaMes")
                        .HasColumnType("int");

                    b.Property<int?>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraExecucao")
                        .HasColumnType("time");

                    b.Property<int>("Intervalo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ModalidadeCobranca")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProximaExecucao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoJob")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaExecucao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("IX_ConfiguracaoAgendamento_Ativo");

                    b.HasIndex("ConfiguracaoCobrancaId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConfiguracaoAgendamento_ConfiguracaoCobrancaId");

                    b.HasIndex("TipoJob")
                        .HasDatabaseName("IX_ConfiguracaoAgendamento_TipoJob");

                    b.ToTable("ConfiguracaoAgendamento", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.ConfiguracaoCobranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AgruparPorPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AgruparPorPlaca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AgruparPorTransportadora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AplicarAcrescimoFixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AplicarDescontoFixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AplicarJuros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AplicarMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CobrarLavagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CobrarPernoite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CobrarServicosExtras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ConsiderarBeneficioAbastecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCobranca")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte?>("DiaFechamento")
                        .HasColumnType("tinyint");

                    b.Property<string>("EmailFinanceiro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EnvioAutomaticoEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EstacionamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("GerarFaturaAutomaticamente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("JurosPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<byte>("ModalidadeCobranca")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("MultaPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("PermitirPagamentoParcial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PrazoVencimentoDias")
                        .HasColumnType("int");

                    b.Property<byte>("RegraFechamento")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAcrescimoFixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("ValorBeneficioAbastecimento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDescontoFixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("ValorEstacionamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorLavagem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorPernoite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorServicosExtras")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EstacionamentoId");

                    b.HasIndex("TransportadoraId", "EstacionamentoId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConfiguracaoCobranca_Transportadora_Estacionamento");

                    b.ToTable("ConfiguracaoCobranca", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AgenciaDigito")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContaDigito")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstacionamentoId")
                        .HasColumnType("int");

                    b.Property<byte?>("TipoChave")
                        .HasColumnType("tinyint");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("TransportadoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstacionamentoId");

                    b.HasIndex("TransportadoraId");

                    b.ToTable("ContaBancaria", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.EntradaSaida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFaturado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataHoraFinalizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataHoraUltimaEntradaPatio")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("EstacionamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("Faturado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Finalizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MotoristaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PermanenciaSuspensa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("TempoPermanenciaMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TempoTotalSuspensaoMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TransportadoraId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioFinalizacaoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioFinalizacaoNome")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("UsuarioRegistroEntradaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioRegistroEntradaNome")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("TransportadoraId");

                    b.HasIndex("VeiculoId");

                    b.HasIndex("EstacionamentoId", "TransportadoraId", "DataHoraSaida")
                        .HasDatabaseName("IX_EntradaSaida_Faturamento")
                        .HasFilter("[Finalizado] = 1 AND [Faturado] = 0");

                    b.ToTable("EntradaSaida", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.EntradaSaidaSuspensao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataHoraFimSuspensao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraInicioSuspensao")
                        .HasColumnType("datetime");

                    b.Property<int>("EntradaSaidaId")
                        .HasColumnType("int");

                    b.Property<int>("TempoSuspensaoMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UsuarioSuspensaoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioSuspensaoNome")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("EntradaSaidaId");

                    b.ToTable("EntradaSaidaSuspensao", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.Estacionamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapacidadeVeiculo")
                        .HasColumnType("int");

                    b.Property<byte?>("CobrancaPorcentagem")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("CobrancaValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Contrato")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Contrato");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descricao");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<bool?>("PossuiBanheiro")
                        .HasColumnType("bit");

                    b.Property<bool?>("PossuiSeguranca")
                        .HasColumnType("bit");

                    b.Property<string>("ResponsavelCpf")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("ResponsavelCpf");

                    b.Property<string>("ResponsavelEmail")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ResponsavelEmail");

                    b.Property<string>("ResponsavelLegal")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ResponsavelLegal");

                    b.Property<string>("ResponsavelTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ResponsavelTelefone");

                    b.Property<string>("TamanhoTerreno")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<byte>("TipoCobranca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Estacionamento", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.EstacionamentoConfiguracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Cultura")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("pt-BR");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EstacionamentoId")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EstacionamentoId")
                        .IsUnique()
                        .HasDatabaseName("IX_EstacionamentoConfiguracao_EstacionamentoId");

                    b.ToTable("EstacionamentoConfiguracao", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.EstacionamentoFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EstacionamentoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Foto")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EstacionamentoId");

                    b.ToTable("EstacionamentoFoto", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfiguracaoCobrancaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmailEnvio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EstacionamentoId")
                        .HasColumnType("int");

                    b.Property<byte?>("ModalidadeRecebimento")
                        .HasColumnType("tinyint");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PeriodoFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodoInicio")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAcrescimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorDesconto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorJuros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorRecebido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracaoCobrancaId");

                    b.HasIndex("DataEmissao");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("EstacionamentoId");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_Fatura_Numero");

                    b.HasIndex("Status");

                    b.HasIndex("TransportadoraId");

                    b.ToTable("Fatura", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.FaturaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraSaida")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("EntradaSaidaId")
                        .HasColumnType("int");

                    b.Property<int>("FaturaId")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("TempoPermanenciaMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("ValorBeneficioAbastecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorEstacionamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorLavagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorPernoite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorServicosExtras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("EntradaSaidaId")
                        .HasDatabaseName("IX_FaturaItem_EntradaSaidaId");

                    b.HasIndex("FaturaId", "EntradaSaidaId")
                        .IsUnique()
                        .HasDatabaseName("IX_FaturaItem_FaturaId_EntradaSaidaId");

                    b.ToTable("FaturaItem", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descricao");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int?>("TransportadoraId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidadeCNH")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TransportadoraId");

                    b.ToTable("Motorista", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeRazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("Pessoa", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.PessoaContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("PessoaContato", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.PessoaEndereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<int>("TipoEndereco")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("PessoaEndereco", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.PessoaPapel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPapel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("PessoaPapel", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.Transportadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descricao");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<string>("ResponsavelCpf")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("ResponsavelCpf");

                    b.Property<string>("ResponsavelEmail")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ResponsavelEmail");

                    b.Property<string>("ResponsavelLegal")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ResponsavelLegal");

                    b.Property<string>("ResponsavelTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ResponsavelTelefone");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Transportadora", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.ToTable("Vaga", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.VagaVeiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descricao");

                    b.Property<int>("VagaId")
                        .HasColumnType("int");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataEntrada");

                    b.HasIndex("VagaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("VagaVeiculo", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Cor")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<byte?>("TipoCarga")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TransportadoraId")
                        .HasColumnType("int");

                    b.Property<int?>("VeiculoDetalheId")
                        .HasColumnType("int");

                    b.Property<int?>("VeiculoModeloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransportadoraId");

                    b.HasIndex("VeiculoModeloId");

                    b.ToTable("Veiculo", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.VeiculoDetalhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CapacidadeArla")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("CapacidadeCombustivel")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("CpfCnpjProprietario")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descricao");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("KmAtual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("KmRastreador")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MediaMaxima")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MediaMinima")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("MEDIAMINIMA");

                    b.Property<string>("NomeProprietario")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.Property<bool>("VeiculoTerceiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId")
                        .IsUnique();

                    b.ToTable("VeiculoDetalhe", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.VeiculoMarca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("VeiculoMarca", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.VeiculoModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descricao");

                    b.Property<int>("VeiculoMarcaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoMarcaId");

                    b.ToTable("VeiculoModelo", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.VeiculoMotorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("int");

                    b.Property<bool?>("Principal")
                        .HasColumnType("bit");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.HasIndex("MotoristaId", "VeiculoId")
                        .IsUnique();

                    b.ToTable("VeiculoMotoristas", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.VeiculoPlaca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.ToTable("VeiculoPlaca", "gts");
                });

            modelBuilder.Entity("Estac.Domain.Models.ConfiguracaoAgendamento", b =>
                {
                    b.HasOne("Estac.Domain.Models.ConfiguracaoCobranca", "ConfiguracaoCobranca")
                        .WithOne("ConfiguracaoAgendamento")
                        .HasForeignKey("Estac.Domain.Models.ConfiguracaoAgendamento", "ConfiguracaoCobrancaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfiguracaoCobranca");
                });

            modelBuilder.Entity("Estac.Domain.Models.ConfiguracaoCobranca", b =>
                {
                    b.HasOne("Estac.Domain.Models.Estacionamento", "Estacionamento")
                        .WithMany()
                        .HasForeignKey("EstacionamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estac.Domain.Models.Transportadora", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estacionamento");

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("Estac.Domain.Models.ContaBancaria", b =>
                {
                    b.HasOne("Estac.Domain.Models.Estacionamento", "Estacionamento")
                        .WithMany("ContasBancarias")
                        .HasForeignKey("EstacionamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estac.Domain.Models.Transportadora", "Transportadora")
                        .WithMany("ContasBancarias")
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Estacionamento");

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("Estac.Domain.Models.EntradaSaida", b =>
                {
                    b.HasOne("Estac.Domain.Models.Estacionamento", "Estacionamento")
                        .WithMany()
                        .HasForeignKey("EstacionamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estac.Domain.Models.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estac.Domain.Models.Transportadora", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Estac.Domain.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estacionamento");

                    b.Navigation("Motorista");

                    b.Navigation("Transportadora");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Estac.Domain.Models.EntradaSaidaSuspensao", b =>
                {
                    b.HasOne("Estac.Domain.Models.EntradaSaida", "EntradaSaida")
                        .WithMany("Suspensoes")
                        .HasForeignKey("EntradaSaidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaSaida");
                });

            modelBuilder.Entity("Estac.Domain.Models.Estacionamento", b =>
                {
                    b.HasOne("Estac.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Estac.Domain.Models.EstacionamentoConfiguracao", b =>
                {
                    b.HasOne("Estac.Domain.Models.Estacionamento", "Estacionamento")
                        .WithOne("Configuracao")
                        .HasForeignKey("Estac.Domain.Models.EstacionamentoConfiguracao", "EstacionamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estacionamento");
                });

            modelBuilder.Entity("Estac.Domain.Models.EstacionamentoFoto", b =>
                {
                    b.HasOne("Estac.Domain.Models.Estacionamento", "Estacionamento")
                        .WithMany("Fotos")
                        .HasForeignKey("EstacionamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamento");
                });

            modelBuilder.Entity("Estac.Domain.Models.Fatura", b =>
                {
                    b.HasOne("Estac.Domain.Models.ConfiguracaoCobranca", "ConfiguracaoCobranca")
                        .WithMany()
                        .HasForeignKey("ConfiguracaoCobrancaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estac.Domain.Models.Estacionamento", "Estacionamento")
                        .WithMany()
                        .HasForeignKey("EstacionamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estac.Domain.Models.Transportadora", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfiguracaoCobranca");

                    b.Navigation("Estacionamento");

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("Estac.Domain.Models.FaturaItem", b =>
                {
                    b.HasOne("Estac.Domain.Models.EntradaSaida", "EntradaSaida")
                        .WithMany()
                        .HasForeignKey("EntradaSaidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estac.Domain.Models.Fatura", "Fatura")
                        .WithMany("Itens")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaSaida");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("Estac.Domain.Models.Motorista", b =>
                {
                    b.HasOne("Estac.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estac.Domain.Models.Transportadora", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pessoa");

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("Estac.Domain.Models.PessoaContato", b =>
                {
                    b.HasOne("Estac.Domain.Models.Pessoa", "Pessoa")
                        .WithMany("Contatos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Estac.Domain.Models.PessoaEndereco", b =>
                {
                    b.HasOne("Estac.Domain.Models.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Estac.Domain.Models.PessoaPapel", b =>
                {
                    b.HasOne("Estac.Domain.Models.Pessoa", "Pessoa")
                        .WithMany("Papeis")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Estac.Domain.Models.Transportadora", b =>
                {
                    b.HasOne("Estac.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Estac.Domain.Models.VagaVeiculo", b =>
                {
                    b.HasOne("Estac.Domain.Models.Vaga", "Vaga")
                        .WithMany("VagaVeiculos")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estac.Domain.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VagaVeiculo_Veiculo");

                    b.Navigation("Vaga");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Estac.Domain.Models.Veiculo", b =>
                {
                    b.HasOne("Estac.Domain.Models.Transportadora", "Transportadora")
                        .WithMany("Veiculos")
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Estac.Domain.Models.VeiculoModelo", "VeiculoModelo")
                        .WithMany()
                        .HasForeignKey("VeiculoModeloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Transportadora");

                    b.Navigation("VeiculoModelo");
                });

            modelBuilder.Entity("Estac.Domain.Models.VeiculoDetalhe", b =>
                {
                    b.HasOne("Estac.Domain.Models.Veiculo", "Veiculo")
                        .WithOne("VeiculoDetalhe")
                        .HasForeignKey("Estac.Domain.Models.VeiculoDetalhe", "VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Estac.Domain.Models.VeiculoModelo", b =>
                {
                    b.HasOne("Estac.Domain.Models.VeiculoMarca", "VeiculoMarca")
                        .WithMany()
                        .HasForeignKey("VeiculoMarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VeiculoMarca");
                });

            modelBuilder.Entity("Estac.Domain.Models.VeiculoMotorista", b =>
                {
                    b.HasOne("Estac.Domain.Models.Motorista", "Motorista")
                        .WithMany("VeiculoMotoristas")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VeiculoMotoristas_Motorista");

                    b.HasOne("Estac.Domain.Models.Veiculo", "Veiculo")
                        .WithMany("VeiculoMotoristas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VeiculoMotoristas_Veiculo");

                    b.Navigation("Motorista");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Estac.Domain.Models.VeiculoPlaca", b =>
                {
                    b.HasOne("Estac.Domain.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Estac.Domain.Models.ConfiguracaoCobranca", b =>
                {
                    b.Navigation("ConfiguracaoAgendamento");
                });

            modelBuilder.Entity("Estac.Domain.Models.EntradaSaida", b =>
                {
                    b.Navigation("Suspensoes");
                });

            modelBuilder.Entity("Estac.Domain.Models.Estacionamento", b =>
                {
                    b.Navigation("Configuracao");

                    b.Navigation("ContasBancarias");

                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Estac.Domain.Models.Fatura", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Estac.Domain.Models.Motorista", b =>
                {
                    b.Navigation("VeiculoMotoristas");
                });

            modelBuilder.Entity("Estac.Domain.Models.Pessoa", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");

                    b.Navigation("Papeis");
                });

            modelBuilder.Entity("Estac.Domain.Models.Transportadora", b =>
                {
                    b.Navigation("ContasBancarias");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("Estac.Domain.Models.Vaga", b =>
                {
                    b.Navigation("VagaVeiculos");
                });

            modelBuilder.Entity("Estac.Domain.Models.Veiculo", b =>
                {
                    b.Navigation("VeiculoDetalhe");

                    b.Navigation("VeiculoMotoristas");
                });
#pragma warning restore 612, 618
        }
    }
}
